version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - bencodezen
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: sort-package-json
    versions:
    - 1.48.1
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
